ARG BASE_IMAGE=ibp-cleansumstats-base:latest

FROM $BASE_IMAGE

WORKDIR /cleansumstats

COPY assets ./assets
COPY bin ./bin
COPY conf ./conf
COPY docs ./docs
COPY environment.yml ./environment.yml
COPY lib ./lib
COPY main.nf ./main.nf
COPY nextflow.config ./nextflow.config

WORKDIR /home/nextflow

ENTRYPOINT ["nextflow", "run", "-offline", "/cleansumstats"]
